// web_app/app/components/stats/StatCard.vue
<script setup lang="ts">
import type { Component } from 'vue'

/**
 * StatCard – a small metric tile used on the Stats page.
 */
defineProps<{
  label: string
  value: string
  unit?: string
  accent?: 'indigo' | 'emerald' | 'amber'
  icon: Component
}>()
</script>

<template>
  <div class="bg-surface rounded-2xl p-4 border border-border flex flex-col gap-3">
    <div class="flex justify-between items-center">
      <span class="text-[10px] text-muted-fg uppercase tracking-wider font-semibold">{{ label }}</span>
      <div
        class="w-8 h-8 rounded-xl flex items-center justify-center"
        :class="{
          'bg-primary-muted text-primary': accent === 'indigo' || !accent,
        }"
        :style="accent === 'emerald'
          ? 'background: var(--accent-emerald-muted); color: var(--accent-emerald);'
          : accent === 'amber'
          ? 'background: var(--accent-amber-muted); color: var(--accent-amber);'
          : ''"
      >
        <component :is="icon" class="w-4 h-4" />
      </div>
    </div>
    <p
      class="text-2xl font-extrabold tabular-nums"
      :class="{
        'text-foreground': accent === 'indigo' || !accent,
      }"
      :style="accent === 'emerald'
        ? 'color: var(--accent-emerald);'
        : accent === 'amber'
        ? 'color: var(--accent-amber);'
        : ''"
    >
      {{ value }}
      <span v-if="unit" class="text-xs font-normal text-muted-fg ml-0.5">{{ unit }}</span>
    </p>
  </div>
</template>

// mobile_app/components/StatCard.tsx
/**
 * StatCard — a metric tile for the Stats page.
 */
import React from 'react';
import { View, Text, StyleSheet } from 'react-native';
import { Timer, Gauge, BookOpen, Flame } from 'lucide-react-native';
import { useTheme } from '../hooks/useTheme';

const iconMap: Record<string, React.ComponentType<any>> = {
  Timer,
  Gauge,
  BookOpen,
  Flame,
};

interface Props {
  label: string;
  value: string;
  unit?: string;
  icon: string;
  accent?: 'indigo' | 'emerald' | 'amber';
}

export default function StatCard({ label, value, unit, icon, accent = 'indigo' }: Props) {
  const { colors } = useTheme();

  const IconComponent = iconMap[icon] || BookOpen;

  const accentColor =
    accent === 'emerald'
      ? colors.accentEmerald
      : accent === 'amber'
      ? colors.accentAmber
      : colors.primary;

  const accentBg =
    accent === 'emerald'
      ? colors.accentEmeraldMuted
      : accent === 'amber'
      ? colors.accentAmberMuted
      : colors.primaryMuted;

  const valueColor = accent === 'indigo' ? colors.foreground : accentColor;

  return (
    <View style={[styles.container, { backgroundColor: colors.surface, borderColor: colors.border }]}>
      <View style={styles.header}>
        <Text style={[styles.label, { color: colors.mutedFg }]}>{label}</Text>
        <View style={[styles.iconWrap, { backgroundColor: accentBg }]}>
          <IconComponent size={16} color={accentColor} />
        </View>
      </View>
      <Text style={[styles.value, { color: valueColor }]}>
        {value}
        {unit ? (
          <Text style={[styles.unit, { color: colors.mutedFg }]}> {unit}</Text>
        ) : null}
      </Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    gap: 12,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  label: {
    fontSize: 10,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  iconWrap: {
    width: 32,
    height: 32,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  value: {
    fontSize: 26,
    fontWeight: '800',
    fontVariant: ['tabular-nums'],
  },
  unit: {
    fontSize: 12,
    fontWeight: '400',
  },
});
