// mobile_app/components/RsvpPlayer.tsx
/**
 * RsvpPlayer — full RSVP reading widget with speed slider, word display, and controls.
 */
import React from 'react';
import { View, Text, Pressable, StyleSheet } from 'react-native';
import Slider from '@react-native-community/slider';
import { Play, Pause, RotateCcw } from 'lucide-react-native';
import RsvpWord from './RsvpWord';
import { useTheme } from '../hooks/useTheme';
import { useTranslation } from 'react-i18next';
import type { FormattedWord } from '../types';

interface Props {
  speed: number;
  isPlaying: boolean;
  formattedWord: FormattedWord;
  onSpeedChange: (v: number) => void;
  onToggle: () => void;
  onReset: () => void;
}

export default function RsvpPlayer({
  speed,
  isPlaying,
  formattedWord,
  onSpeedChange,
  onToggle,
  onReset,
}: Props) {
  const { colors } = useTheme();
  const { t } = useTranslation();

  return (
    <View style={[styles.container, { backgroundColor: colors.surface2, borderColor: colors.border }]}>
      {/* Speed header */}
      <View style={styles.speedHeader}>
        <Text style={[styles.label, { color: colors.mutedFg }]}>{t('rsvpPlayer.preview')}</Text>
        <Text style={[styles.speedValue, { color: colors.primary }]}>{speed} WPM</Text>
      </View>

      {/* Slider */}
      <View style={styles.sliderWrap}>
        <Slider
          value={speed}
          minimumValue={100}
          maximumValue={800}
          step={25}
          onValueChange={onSpeedChange}
          minimumTrackTintColor={colors.primary}
          maximumTrackTintColor={colors.surface3}
          thumbTintColor={colors.primary}
          style={styles.slider}
        />
      </View>

      {/* Word display */}
      <View style={[styles.wordWindow, { backgroundColor: colors.background, borderColor: colors.border }]}>
        {/* ORP guides */}
        <View style={[styles.orpLine, { backgroundColor: colors.primaryMuted }]} />
        <View style={[styles.orpDot, styles.orpDotTop, { backgroundColor: colors.primaryMuted }]} />
        <View style={[styles.orpDot, styles.orpDotBottom, { backgroundColor: colors.primaryMuted }]} />

        <RsvpWord word={formattedWord} fontSize={22} />
      </View>

      {/* Controls */}
      <View style={styles.controls}>
        <Pressable
          onPress={onToggle}
          style={[styles.playBtn, { backgroundColor: colors.primary }]}
        >
          {isPlaying ? (
            <Pause size={18} color={colors.primaryFg} fill={colors.primaryFg} />
          ) : (
            <Play size={18} color={colors.primaryFg} fill={colors.primaryFg} />
          )}
          <Text style={[styles.playBtnText, { color: colors.primaryFg }]}>
            {isPlaying ? t('rsvpPlayer.pause') : t('rsvpPlayer.play')}
          </Text>
        </Pressable>

        <Pressable
          onPress={onReset}
          style={[styles.resetBtn, { backgroundColor: colors.surface3, borderColor: colors.border }]}
        >
          <RotateCcw size={18} color={colors.foreground} />
        </Pressable>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
  },
  speedHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  label: {
    fontSize: 12,
    fontWeight: '500',
  },
  speedValue: {
    fontSize: 12,
    fontWeight: '700',
    fontVariant: ['tabular-nums'],
  },
  sliderWrap: {
    marginBottom: 16,
  },
  slider: {
    width: '100%',
    height: 32,
  },
  wordWindow: {
    height: 64,
    borderRadius: 14,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
    overflow: 'hidden',
  },
  orpLine: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: '50%',
    width: 1,
  },
  orpDot: {
    position: 'absolute',
    left: '50%',
    marginLeft: -3,
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  orpDotTop: {
    top: 6,
  },
  orpDotBottom: {
    bottom: 6,
  },
  controls: {
    flexDirection: 'row',
    gap: 8,
  },
  playBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 12,
    borderRadius: 14,
  },
  playBtnText: {
    fontSize: 13,
    fontWeight: '700',
  },
  resetBtn: {
    width: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
    borderWidth: 1,
  },
});

// web_app/app/components/rsvp/RsvpPlayer.vue
<script setup lang="ts">
/**
 * RsvpPlayer – full RSVP reading widget:
 * speed slider, word display window, play/pause and reset controls.
 */
import { Slider } from '~/components/ui/slider'
import { Button } from '~/components/ui/button'
import { useRsvp } from '~/composables/useRsvp'
import RsvpWord from '~/components/rsvp/RsvpWord.vue'
import { LucidePause, LucidePlay, LucideRotateCcw } from 'lucide-vue-next'

const { t } = useI18n()
const { speed, isPlaying, formattedWord, toggle, reset } = useRsvp()

// shadcn Slider uses number[] for v-model
const speedArray = computed({
  get: () => [speed.value],
  set: (val: number[]) => { speed.value = val[0] },
})
</script>

<template>
  <div class="bg-surface-2 rounded-2xl p-4 border border-border">

    <!-- Speed header -->
    <div class="flex justify-between items-center mb-3">
      <span class="text-xs text-muted-fg font-medium">{{ $t('rsvpPlayer.preview') }}</span>
      <span class="text-xs font-bold text-primary tabular-nums">{{ speed }} WPM</span>
    </div>

    <!-- Slider -->
    <Slider
      v-model="speedArray"
      :min="100"
      :max="800"
      :step="25"
      class="mb-4"
      :aria-label="$t('rsvpPlayer.readingSpeed')"
    />

    <!-- Word display -->
    <div
      class="h-16 bg-background rounded-xl flex items-center justify-center relative overflow-hidden border border-border mb-3"
      role="region"
      aria-label="Okno RSVP"
      aria-live="assertive"
    >
      <!-- ORP guides -->
      <div class="absolute top-0 bottom-0 left-1/2 w-px bg-primary/10 pointer-events-none" />
      <div class="absolute top-1.5 left-1/2 -translate-x-1/2 w-1.5 h-1.5 rounded-full bg-primary/25 pointer-events-none" />
      <div class="absolute bottom-1.5 left-1/2 -translate-x-1/2 w-1.5 h-1.5 rounded-full bg-primary/25 pointer-events-none" />

      <RsvpWord :word="formattedWord" />
    </div>

    <!-- Controls -->
    <div class="flex gap-2">
      <Button
        id="rsvp-toggle-btn"
        class="flex-1 py-2.5 bg-primary hover:bg-primary-hover text-primary-fg font-semibold text-xs rounded-xl gap-1.5"
        @click="toggle"
      >
        <component :is="isPlaying ? 'LucidePause' : 'LucidePlay'" class="w-4 h-4 fill-current" />
        {{ isPlaying ? $t('rsvpPlayer.pause') : $t('rsvpPlayer.play') }}
      </Button>
      <Button
        id="rsvp-reset-btn"
        variant="secondary"
        class="px-3 bg-surface-3 hover:bg-surface-2 text-foreground rounded-xl border border-border"
        :aria-label="$t('rsvpPlayer.reset')"
        @click="reset"
      >
        <LucideRotateCcw class="w-4 h-4" />
      </Button>
    </div>
  </div>
</template>
