// web_app/app/pages/stats.vue
<script setup lang="ts">
import StatCard from '~/components/stats/StatCard.vue'
import { LucideBarChart2, LucideTimer, LucideGauge, LucideBookOpen, LucideFlame } from 'lucide-vue-next'

const { t } = useI18n()

useSeoMeta({
  title: computed(() => `RSVP Reader – ${t('stats.title')}`),
  description: computed(() => t('stats.subtitle')),
})

const { data: stats } = useAsyncData('stats', () => $fetch<any>('/api/stats'))
</script>

<template>
  <div class="flex-1 overflow-y-auto pb-28">

    <!-- ─── Header ────────────────────────────────────────────── -->
    <header class="px-5 pt-6 pb-4">
      <h1 class="text-2xl font-extrabold text-foreground tracking-tight">{{ $t('stats.title') }}</h1>
      <p class="text-xs text-muted-fg mt-0.5">{{ $t('stats.subtitle') }}</p>
    </header>

    <!-- ─── Siatka statystyk ──────────────────────────────────── -->
    <section class="px-5">
      <div class="grid grid-cols-2 gap-3">
        <StatCard
          :label="$t('stats.totalTime')"
          :value="String(stats?.totalMinutes ?? 0)"
          :unit="$t('stats.unit.min')"
          :icon="LucideTimer"
          accent="indigo"
        />
        <StatCard
          :label="$t('stats.maxSpeed')"
          :value="String(stats?.maxWpm ?? 0)"
          :unit="$t('stats.unit.wpm')"
          :icon="LucideGauge"
          accent="emerald"
        />
        <StatCard
          :label="$t('stats.books')"
          :value="String(stats?.booksCount ?? 0)"
          :unit="$t('stats.unit.pcs')"
          :icon="LucideBookOpen"
          accent="indigo"
        />
        <StatCard
          :label="$t('stats.streak')"
          :value="String(stats?.streak ?? 0)"
          :unit="$t('stats.unit.days')"
          :icon="LucideFlame"
          accent="amber"
        />
      </div>
    </section>

    <!-- ─── Puste stany ───────────────────────────────────────── -->
    <section
      v-if="!stats?.totalMinutes"
      class="px-5 mt-6"
    >
      <div class="bg-surface rounded-2xl border border-border p-8 text-center">
        <LucideBarChart2 class="w-10 h-10 mx-auto mb-3 text-muted-fg opacity-40" />
        <p class="text-sm font-semibold text-foreground mb-1">{{ $t('stats.noData') }}</p>
        <p class="text-xs text-muted-fg">
          {{ $t('stats.noDataDesc') }}
        </p>
      </div>
    </section>

  </div>
</template>

// mobile_app/app/(tabs)/stats.tsx
import React, { useState, useEffect, useCallback } from 'react';
import { View, Text, ScrollView, StyleSheet, RefreshControl } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { BarChart2 } from 'lucide-react-native';
import { useTranslation } from 'react-i18next';
import { useTheme } from '../../hooks/useTheme';
import StatCard from '../../components/StatCard';
import * as db from '../../db/database';
import type { Stats } from '../../types';

export default function StatsScreen() {
  const { t } = useTranslation();
  const { colors } = useTheme();
  const [stats, setStats] = useState<Stats>({
    totalMinutes: 0,
    maxWpm: 0,
    booksCount: 0,
    streak: 0,
    totalWordsRead: 0,
  });
  const [refreshing, setRefreshing] = useState(false);

  const loadStats = useCallback(async () => {
    try {
      const data = await db.getStats();
      setStats(data);
    } catch (e) {
      console.error('Failed to load stats:', e);
    }
  }, []);

  useEffect(() => {
    loadStats();
  }, [loadStats]);

  const onRefresh = useCallback(async () => {
    setRefreshing(true);
    await loadStats();
    setRefreshing(false);
  }, [loadStats]);

  return (
    <SafeAreaView style={[styles.safeArea, { backgroundColor: colors.background }]}>
      <ScrollView
        contentContainerStyle={styles.container}
        refreshControl={<RefreshControl refreshing={refreshing} onRefresh={onRefresh} tintColor={colors.primary} />}
      >
        {/* Header */}
        <View style={styles.header}>
          <Text style={[styles.title, { color: colors.foreground }]}>{t('stats.title')}</Text>
          <Text style={[styles.subtitle, { color: colors.mutedFg }]}>
            {t('stats.subtitle')}
          </Text>
        </View>

        {/* 2x2 Grid */}
        <View style={styles.grid}>
          <View style={styles.gridItem}>
            <StatCard
              label={t('stats.totalTime')}
              value={String(stats.totalMinutes)}
              unit={t('stats.unit.min')}
              icon="Timer"
              accent="indigo"
            />
          </View>
          <View style={styles.gridItem}>
            <StatCard
              label={t('stats.maxSpeed')}
              value={String(stats.maxWpm)}
              unit={t('stats.unit.wpm')}
              icon="Gauge"
              accent="emerald"
            />
          </View>
          <View style={styles.gridItem}>
            <StatCard
              label={t('stats.books')}
              value={String(stats.booksCount)}
              unit={t('stats.unit.pcs')}
              icon="BookOpen"
              accent="indigo"
            />
          </View>
          <View style={styles.gridItem}>
            <StatCard
              label={t('stats.streak')}
              value={String(stats.streak)}
              unit={t('stats.unit.days')}
              icon="Flame"
              accent="amber"
            />
          </View>
        </View>

        {/* Empty state when no reading time */}
        {stats.totalMinutes === 0 && (
          <View style={[styles.emptyBox, { backgroundColor: colors.surface, borderColor: colors.border }]}>
            <BarChart2 size={40} color={colors.mutedFg} style={{ opacity: 0.4, marginBottom: 12 }} />
            <Text style={[styles.emptyTitle, { color: colors.foreground }]}>{t('stats.noData')}</Text>
            <Text style={[styles.emptyDesc, { color: colors.mutedFg }]}>
              {t('stats.noDataDesc')}
            </Text>
          </View>
        )}
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  container: {
    padding: 20,
    paddingBottom: 30,
    gap: 16,
  },
  header: {
    paddingTop: 12,
    marginBottom: 4,
  },
  title: {
    fontSize: 24,
    fontWeight: '800',
  },
  subtitle: {
    fontSize: 12,
    marginTop: 2,
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  gridItem: {
    width: '48%',
  },
  emptyBox: {
    borderRadius: 24,
    padding: 32,
    borderWidth: 1,
    alignItems: 'center',
    marginTop: 8,
  },
  emptyTitle: {
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 4,
  },
  emptyDesc: {
    fontSize: 12,
    textAlign: 'center',
  },
});
